### ISSUE TITLE
Allow 'set position' to use decimals

### ISSUE THREAD

**Issue by jones-d** [pink88/Tuiss2HA#24]
I have this add-on working correctly, but I am looking to see if you can do an enhancement request to allow decimal points.  As we have double blinds (the ones with panels and then sheer, minor adjustments to let more light in), I would like to make small adjustments.  In the Tuiss app, you can do 97.4%, which aligns the panels perfectly.  In the 'set position', it will only allow 97 or 98.  Can this be allowed in the add-on?

Here is an image from the app.
![IMG_4961](https://github.com/user-attachments/assets/16288821-a7a8-47af-b2df-504dd3cdc5ea)

**Comment by pink88** [comment]
I'll take a look at this at the weekend and get back to you

**Comment by pink88** [comment]
Looking into this and Home Assistant only allow whole number values to set
a blind position, so unless they make a change, there isn't anything that I
can do unfortunately.
Cover - Home Assistant
<https://www.home-assistant.io/integrations/cover/#action-coverset_cover_position>

**Comment by jones-d** [comment]
Thank you for looking. I am using an automation where I can pass any value. Does this open up an option?Many thanksDaveOn 20 Nov 2024, at 16:31, pink88 ***@***.***> wrote:﻿
Looking into this and Home Assistant only allow whole number values to set

a blind position, so unless they make a change, there isn't anything that I

can do unfortunately.

Cover - Home Assistant

<https://www.home-assistant.io/integrations/cover/#action-coverset_cover_position>

**Comment by pink88** [comment]
Unfortunately that won't make a difference as it's baked into the home
assistant blind logic, which this integration is only leveraging. If you
wanted it to support decimals, that would be a request to the core HA team.

There might be some other options though, depending on what the Tuiss app
is sending out. Can you share the model # type of blind you have and if the
app offers a separate tilt control or is this all just within the decimal
increments as you set the open/close position?

**Comment by jones-d** [comment]
What is the best way to find the model number of the blind?The app you have a toggle for the tilt, but you can just send the percentage as well. CheersDaveOn 21 Nov 2024, at 11:18, pink88 ***@***.***> wrote:﻿
Unfortunately that won't make a difference as it's baked into the home

assistant blind logic, which this integration is only leveraging. If you

wanted it to support decimals, that would be a request to the core HA team.



There might be some other options though, depending on what the Tuiss app

is sending out. Can you share the model # type of blind you have and if the

app offers a separate tilt control or is this all just within the decimal

increments as you set the open/close position?

**Comment by pink88** [comment]
If you go into your phone or computers Bluetooth and search for devices you
should see your blind as TS_____. If you can share that and a link to the
product you purchased, that would be great.

**Comment by jones-d** [comment]
They are TS2600 and here is the linkElectric Enjoy Luxe White Roller Blindblinds-2go.co.ukOn 22 Nov 2024, at 23:50, pink88 ***@***.***> wrote:﻿
If you go into your phone or computers Bluetooth and search for devices you

should see your blind as TS_____. If you can share that and a link to the

product you purchased, that would be great.

**Comment by jones-d** [comment]
[Update.zip](https://github.com/user-attachments/files/17879734/Update.zip)
I have been able to create a new service to set the blinds to the correct decimal point.  Here are the two files.

**Comment by pink88** [comment]
Fixed in with #25
